### ISSUE TITLE
Add contents what you are doing now to README.md

### ISSUE THREAD

**Issue by somniumism** [lizard-kim/TIL#1]
As you know, you can use [markdown checkbox](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists).

You can introduce the project to many people, and can also make plans for what you are learning.

Example:

**19. 12. 24 TODO:**
- [x] Implement a function to print "hello_world"
- [x] Fix Bug

**20. 11. 24 TODO:**
- [x] Delete All Project
- [x] Drop out of school.

Of course, I didn't do this. 😆 However, I think this will be good for you.

Good luck, my friend : )

**Comment by lizard-kim** [comment]
good point!
thanks for your advice!
I will apply your comment. :)
